name: Override environment variable
on: push
env:
  EXAMPLE: Defined by workflow level  # This is a workflow-level environment variable
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${EXAMPLE}"  # This will print the workflow-level variable
            
            - run: echo "${EXAMPLE}"
              env:
                EXAMPLE: Defined by step level
